name: Museum Tender Notifier

on:
  schedule:
    - cron: '30 1 * * *'  # 每天 UTC 时间 01:30，约等于北京时间 09:30
  workflow_dispatch:      # 支持手动触发

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and setup Chrome & chromedriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Run scraper
        env:
          WECHAT_WEBHOOK_URL: ${{ secrets.WECHAT_WEBHOOK_URL }}
        run: |
          export CHROME_BIN=$(which chrome)
          export CHROMEDRIVER=$(which chromedriver)
          python tender_notifier.py
